#include: package:flutter_lints/flutter.yaml

linter:
  rules:
    valid_regexps: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: false
    prefer_const_literals_to_create_immutables: false
    constant_identifier_names: false
    use_key_in_widget_constructors: false