name: out_out
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.6+86
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  cupertino_icons: ^1.0.3
  device_preview: ^1.1.0
  dio: ^5.1.2
  dotted_line: ^3.0.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_dynamic_links: ^5.4.4
  firebase_messaging: ^14.7.4
  app_links: ^3.4.3
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_facebook_auth: ^5.0.11
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.8.0
  font_awesome_flutter: ^10.6.0
  geocoding:
  geolocator:
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^6.1.5
  hive: 
  hive_flutter: 
  image_picker: ^1.0.4
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.0.0
  package_info: ^2.0.2
  path_provider: 
  pin_code_fields: ^8.0.1
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  retrofit: ^4.0.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sign_in_with_apple: ^5.0.0
  synchronized: ^3.0.0
  timeago: ^3.0.2
  url_launcher: ^6.0.3
  webview_flutter: ^4.4.1
  geolocator_android: ^4.1.8
  permission_handler: ^11.0.1

dev_dependencies:
  build_runner: ^2.0.3
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.1
  test: ^1.17.5

flutter:
  uses-material-design: true

  assets:
    - assets/pictures/images/
    - assets/pictures/icons/
    - assets/pictures/logos/
    - assets/google_maps_style.json
    - assets/default_payment_profile_apple_pay.json